### PR TITLE
Show package names in the output. Build with 8.0.1.

### PR DESCRIPTION
**Pull request by osa1**
I don't expect this to be merged (breaks the build for older GHCs), but wanted to put this here in case someone finds this useful.

### CODE REVIEW

**Comment by Gonzih** [comment]
Meh, I will just merge it in.

**Comment by Gonzih** [comment]
So I tried to build this, sadly build fails. Both on my machine and on travis ci. Can you specify your build environment?

**Comment by osa1** [comment]
You need GHC 8.0.1.

**Comment by Gonzih** [comment]
Yeah, was my local cabal cache issues. Will port travis build in to docker i guess, because otherwise it's a mess.

**Pull request merged**
